<?php /** @var \Klevu\Search\Block\Search\Index $block */?>
<?php 
	$store_id = $block->getStoreParam();
	$rest_api = $block->getRestApiParam();
	$rest_from_db = $block->getRestApi($store_id);
?>
<div id="info_message"><span id="loader" style="display:none">Please wait...</span></div>

<script type="text/javascript">
<?php if($rest_api == $rest_from_db) { ?>
require(['jquery'], function(){
        callAjaxRecurrsively();
});
<?php } else { ?>
	     alert('<?php echo $rest_api."</br>".$rest_api;?>');
<?php } ?>

function callAjaxRecurrsively(){
	jQuery.ajax({
            url:'<?php echo $block->getBaseUrl(); ?>/search/index/syncstoreview/store/'+<?php echo $store_id; ?>+'/restapi/'+'<?php echo $rest_api; ?>',
            type: 'GET',
            dataType: 'json',
			beforeSend: function(){
				// Show image container
				document.getElementById("loader").style.display = "block";
		   	},
			success:function(data) {
					if(data.numberOfRecord_add != 0 || data.numberOfRecord_update != 0 || data.numberOfRecord_delete != 0) {
						document.getElementById("loader").style.display = "none";
					    var str = "Next batch sent to klevu";
						document.getElementById("info_message").innerHTML += str+"</br>";
						callAjaxRecurrsively();
					} else{
						var str = "No records found to sync";
						document.getElementById("info_message").innerHTML += str+"</br>";
					}
    		},
            crossDomain: true
         });
}

</script>

