<?php /** @var \Klevu\Search\Block\Search\Index $block */ ?>
<?php
$store_id = (int)$block->getStoreParam();
$key = $block->getRestApiParam();
$rest_from_db = $block->getRestApi($store_id);
$indexersMessage = $block->isShowIndexerMessage();
?>
<?php if ($key !== $rest_from_db): ?>
    <div class="message warning" id="kl_invalid_hash_key">
        <span>
            <?= __('Hash key found invalid for requested store.') ?>
        </span>
    </div>
<?php else: ?>
    <?php if ($indexersMessage): ?>
        <div class="message warning" id="kl_indexers_message">
            <span>
                <?= __('Magento Indexers are found invalid for the Magento Store.') ?>
                <?= __(
                    'Please rebuild %1 Magento Indexers %2 and Click on %1 Sync Updates Only for This Store %2 again..',
                    '<strong>',
                    '</strong>'
                ) ?>
            </span>
        </div>
    <?php endif; ?>
    <div class="message warning" id="kl_close_warning_before" style="display:block">
        <span>
            <?= __('Please don\'t close this tab when the data is being synchronized.') ?>
        </span>
    </div>
    <div class="message success" id="kl_close_warning_after" style="display:none">
        <span>
            <?= __('Data Synchronization has been finished. You can close this tab now.') ?>&nbsp;
            <a title="<?= __('By clicking on link, it will close tab') ?>"
               href="#"
               onclick="window.close(); return false;">
                <?= __('Click to close tab') ?>
            </a>
        </span>
    </div>
    <div id="info_message">
        <span id="loader" style="display:none">
            <?= __('Please wait...') ?>
        </span>
    </div>

    <script type="text/javascript">
        function callAjaxRecurrsively() {
            document.getElementById("loader").style.display = "block";

            const url = '<?= $block->escapeUrl(
                sprintf('%s/search/index/syncstoreview/store/%s/hashkey/', $block->getBaseUrl(), $store_id)
            ) . $key ?>';

            fetch(url, {
                method: 'GET',
                crossDomain: true
            }).then((response) => response.json()).then((data) => {
                let htmlToDisplay;
                if (data.numberOfRecord_add == null &&
                    data.numberOfRecord_update == null &&
                    data.numberOfRecord_delete == null
                ) {
                    htmlToDisplay = '<br />';
                    htmlToDisplay += '<div class="message warning">';
                    htmlToDisplay += '<span>';
                    htmlToDisplay += '<?= __('Something went wrong with the sync. Please see Klevu_Search.log file for further information.') ?>';
                    if (data.msg != null) {
                        htmlToDisplay += '<br />' + data.msg;
                    }
                    htmlToDisplay += '</span>';
                    htmlToDisplay += '</div>';
                    htmlToDisplay += "<br />"

                    document.getElementById("info_message").innerHTML += htmlToDisplay;
                } else if (parseInt(data.numberOfRecord_add) !== 0 ||
                    parseInt(data.numberOfRecord_update) !== 0 ||
                    parseInt(data.numberOfRecord_delete) !== 0
                ) {
                    htmlToDisplay = "<?= __('Next batch sent to Klevu') ?>";
                    htmlToDisplay += "<br />"

                    document.getElementById("info_message").innerHTML += htmlToDisplay;
                    callAjaxRecurrsively();
                } else {
                    htmlToDisplay = "<?= __('No records found to sync') ?>";
                    htmlToDisplay += "<br />"

                    document.getElementById("info_message").innerHTML += htmlToDisplay;
                    document.getElementById("kl_close_warning_before").style.display = "none";
                    document.getElementById("kl_close_warning_after").style.display = "block";
                }
                document.getElementById("loader").style.display = "none";
            });
        }

        callAjaxRecurrsively();
    </script>
<?php endif; ?>
