<?php
/**
 * @var Klevu\Search\Block\Search\CssIncludes $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?= $secureRenderer->renderTag(
    'link',
    [
        'type' => 'text/css',
        'media' => 'all',
        'rel' => 'stylesheet',
        'href' => $block->getViewFileUrl("Klevu_Search::css/klevu-landing-page-style.css"),
    ]
) ?>

<?= $secureRenderer->renderTag(
    'link',
    [
        'type' => 'text/css',
        'media' => 'all',
        'rel' => 'stylesheet',
        'href' => $block->getViewFileUrl("Klevu_Search::css/klevu-landing-responsive.css"),
    ]
) ?>
