<?php
/**
 * @var \Klevu\Search\Block\Search\Index $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php if ($block->isExtensionConfigured()) : ?>
    <?php
    $url = $block->getUrl('search', ['_secure' => $block->getRequest()->isSecure()]);
    $landingTheme = (int)$block->isLandingEnabled();
    $scriptString = "
    // add in cms template
    var klevu_current_version = '{$block->getModuleInfo()}';
    var allInputs = document.getElementsByTagName('input');
    ";
    if ($landingTheme === $block::DISABLE) {
        $scriptString .= "
        var klevu_showQuickSearchOnEnter = true;
        (function () {
            // Remove Magento event observers from the search box
            // No Redirection of landing page
            for (i = 0, len = allInputs.length; i < len; i++) {
                if (allInputs[i].type === 'text' || allInputs[i].type === 'search') {
                    if (allInputs[i].name === 'q' || allInputs[i].id === 'search') {
                        var search_input = allInputs[i];
                        search_input.form.onsubmit = function () {
                            return false;
                        };
                    }
                }
            }
        })();
        ";
    } elseif ($landingTheme === $block::KlEVUTEMPLATE) {
        $scriptString .= "
        (function () {
            // Remove Magento event observers from the search box
            // Redirect to klevu js page
            for (i = 0, len = allInputs.length; i < len; i++) {
                if (allInputs[i].type === 'text' || allInputs[i].type === 'search') {
                    if (allInputs[i].name === 'q' || allInputs[i].id === 'search') {
                        var search_input = allInputs[i];
                        search_input.form.action = '{$url}';
                    }
                }
            }
        })();
        var klevu_storeLandingPageUrl = '{$url}';
        var klevu_showQuickSearchOnEnter = false;
        ";
    } elseif ($landingTheme === $block::KlEVUPRESERVELAYOUT) {
        $scriptString .= "
        (function () {
            // Remove Magento event observers from the search box
            // default Magento layout landing page
            for (i = 0, len = allInputs.length; i < len; i++) {
                if (allInputs[i].type === 'text' || allInputs[i].type === 'search') {
                    if (allInputs[i].name === 'q' || allInputs[i].id === 'search') {
                        var search_input = allInputs[i];
                    }
                }
            }
        })();
        var klevu_storeLandingPageUrl = '{$block->getUrl(
            'catalogsearch/result',
            ['_secure' => $block->getRequest()->isSecure()]
        )}';
        var klevu_showQuickSearchOnEnter = false;
        ";
    }

$scriptString .= "
    // call store js
    var klevu_apiKey = '{$block->getJsApiKey()}',
        searchTextBoxName = 'search',
        klevu_lang = '{$block->getStoreLanguage()}',
        klevu_result_top_margin = '',
        klevu_result_left_margin = '';
    (function () {
        var ws = document.createElement('script'),
            kl_protocol = ('https:' === document.location.protocol ? 'https://' : 'http://');
        ws.type = 'text/javascript';
        ws.async = true;
        ws.src = kl_protocol + '{$block->getJsUrl()}/klevu-js-v1/js/klevu-webstore.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ws, s);
    })();
    ";
    ?>
    <?= $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        $scriptString,
        false
    ) ?>

    <?php
    $currency = $block->getCurrencyData();
    $pubIsInUse = $block->isPubInUse() ? "true" : "false";
    $currencyScriptString = "

    if (typeof klevu_baseCurrencyCode === 'undefined') {
        var klevu_baseCurrencyCode = '{$block->escapeJsQuote($block->getBaseCurrencyCode())}';
    }
    if (typeof klevu_currentCurrencyCode === 'undefined') {
        var klevu_currentCurrencyCode = '{$block->escapeJsQuote($block->getCurrentCurrencyCode())}';
    }
    ";

    if ($currency) {
        $currencyScriptString .= "
            if (typeof klevu_currentCurrencyRates === 'undefined') {
                var klevu_currentCurrencyRates = {{$currency}};
            }
        ";
    }

    $currencyScriptString .= "

    klevu_pubIsInUse = $pubIsInUse;
    if (!(typeof klevu_uc_productCustomizations === 'function' && typeof klevu_uc_productCustomizations.nodeType !== 'number')) {
        function klevu_uc_productCustomizations(product) {
            if (klevu_pubIsInUse) {
                // maintained for products that have not been re-synced since the removal of need to change from indexing
                product.productImage = product.productImage.replace('pub/', '');
                product.productImage = product.productImage.replace('needtochange/', '');
            } else {
                product.productImage = product.productImage.replace('needtochange/', 'pub/');
            }

            if ('undefined' !== typeof klevuMagentoCustomerGroupFlag && klevuMagentoCustomerGroupFlag == false) {
                product.productPrice = '0';
                product.startPrice = '0';
                product.toPrice = '0';
                product.salePrice = '0';
            }

            return product;
        }
    }
    ";
    ?>
    <?= $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        $currencyScriptString,
        false
    ) ?>
<?php endif; ?>
