<?php /** @var \Klevu\Search\Block\Search\Index $block */ ?>

<?php $per_page = $block->getGridPerPageValues(); ?>
<?php $grid_per_page = (int)$block->getGridPerPage(); ?>


<div class="kuContainer" id="kuMainContainer">
  <div id="loader" style="text-align:center"><img src="<?php echo $block->getViewFileUrl('Klevu_Search::images/klevu/ku-loader.gif'); ?>" alt="Loading..."/></div>
  <div class="kuNoRecordFound" id="kuNoRecordFound" style="display:none;">
    <p><?php echo __('No matching products found.');?></p>
  </div>
  <div class="kuProListing" id="kuProListing" style="display: none;">
    <div class="kuFilters" id="kuFilters">

    </div><!-- End of kuFilters -->

    <div class="kuResultList" id="kuResultListBlock">
      <div class="kuResultInfo">
        <div class="kuTotalResultsTab" id="kuTotResults">
          <div class="kuTabs" id="kuTabs">
          </div>
        </div>

        <div class="kuPagination" id="kuPagination1">
        </div>
        <div class="kuPagination" id="kuPagination3" style="display:none;">
        </div>

        <div class="kuClearBoth"></div>
      </div>

      <div class="kuProductContent" id="kuProductContent">
        <div class="kuSortHeader">
          <div class="kuSortingOpt">
            <div class="kuSortby">
                <label id="klevuSortLbl"><?php echo __('Sort by');?>:</label>
                <?php $configurableSortByHtml = $block->getChildHtml('configurable_sortby'); ?>
                <?php if (trim((string)$configurableSortByHtml)): ?>
                    <?php /** @noEscape  */ echo $configurableSortByHtml; ?>
                <?php else: ?>
                    <select name="kuSortby" id="kuSortby" onchange="klevu_changeSortingOptionsForLandigPage(this.value);">
                        <option id="klevuRelSort" value="rel"><?php echo $block->escapeHtml(__('Relevance'));?></option>
                        <option id="klevuLthSort" value="lth"><?php echo $block->escapeHtml(__('Price').":".__('Low to high'));?></option>
                        <option id="klevuHtlSort" value="htl"><?php echo $block->escapeHtml(__('Price').":".__('High to low'));?></option>
                    </select>
                <?php endif; ?>
            </div>

            <div class="kuPerPage">
              <label id="klevuItemsPerPage"><?php echo __('Items per page');?>:</label>
              <select onchange="klevu_changeItemsPerPage(this.value);" id="noOfRecords1">

                    <?php if(!empty($per_page)): ?>
                        <?php foreach($per_page as $key => $value): ?>
                            <option> <?php echo $value;?></option>
                        <?php endforeach; ?>
                    <?php endif; ?>
              </select>
            </div>

            <div class="kuView">
              <a class="kuGridviewBtn kuCurrent" id="gridViewBtn" onclick="klevu_setKuView('grid');">
                <span class="icon-gridview"></span>
              </a>
              <a class="kuListviewBtn" id="listViewBtn" onclick="klevu_setKuView('list');">
                <span class="icon-listview"></span>
              </a>
            </div>

            <div class="kuClearLeft"></div>
          </div>

        </div>

        <div class="kuGridView" id="kuResultsView">

        </div><!-- End of klevuResults-->

        <div class="kuBottomPagi">
          <div class="kuPerPage">
            <label id="klevuItemsPerPageFooter"><?php echo __('Items per page');?>:</label>
            <select onchange="klevu_changeItemsPerPage(this.value);" id="noOfRecords2">
                <?php if(!empty($per_page)): ?>
                    <?php foreach($per_page as $key => $value): ?>
                        <option><?php echo $value;?></option>
                  <?php endforeach; ?>
                <?php endif; ?>
            </select>
          </div>

          <div class="kuPagination" id="kuPagination2">

          </div>
          <div class="kuClearBoth"></div>
        </div>
      </div> <!-- End of product content -->

      <!-- Other content -->

      <div class="kuOtherContent" id="kuOtherContent">
        <div class="kuSortHeader">
          <div class="kuSortingOpt">
            <div class="kuPerPage">
              <label id="klevuItemsPerPageCms"><?php echo __('Items per page');?>:</label>
              <select onchange="klevu_changeCmsItemsPerPage(this.value);" id="noOfRecords3">
                <option>12</option>
                <option>24</option>
                <option>36</option>
              </select>
            </div>
            <div class="kuClearLeft"></div>
          </div>
        </div>

        <div class="kuListView kuOtherContentView" id="kuOtherContentView">
        </div>

        <div class="kuSortHeader">
          <div class="kuSortingOpt">
            <div class="kuPerPage">
              <label id="klevuItemsPerPageCmsFooter"><?php echo __('Items per page');?>:</label>
              <select onchange="klevu_changeCmsItemsPerPage(this.value);" id="noOfRecords4">
                <option>12</option>
                <option>24</option>
                <option>36</option>
              </select>
            </div>
            <div class="kuPagination" id="kuPagination4">
            </div>
            <div class="kuClearLeft"></div>
          </div>
        </div>
      </div>
      <!-- End of other content -->

    </div>
    <div class="kuClearBoth"></div>
  </div><!-- End of kuProListing -->
</div><!-- End of klevu-container -->


<input id="noOfRecords" type="hidden" name="noOfRecords" value="<?php echo $grid_per_page; ?>" />
<input type="hidden" name="startPos" id="startPos" value="0"/>
<input type="hidden" name="totalResultsFound" id="totalResultsFound" value="0"/>
<input type="hidden" name="searchedKeyword" id="searchedKeyword" value=""/>
<input type="hidden" name="totalPages" id="totalPages" value="0"/>
<?php
$isSecure = $block->getRequest()->isSecure();
$protocol = ($isSecure) ? 'https://' : 'http://';
$src = $protocol.$block->getJsUrl();
?>
<script type="text/javascript" src="<?php echo $src; ?>/klevu-js-v1/js-1-1/klevu-landing.js">// <![CDATA[
// ]]></script>
<script type="text/javascript">// <![CDATA[
document.getElementById("searchedKeyword").value= klevu_getParamValue("q");
// ]]></script>
<?php if($block->isCustomerGroupPriceEnabled()) { ?>
    <script type="text/javascript">
            var counter = 0;
            var klevuMagentoCustomerGroupFlag = false;
            var timeKlevuUpdate = setInterval(function () {
                var elem = document.getElementById('klevu_sessionId');
                if(elem !== null && elem.innerHTML) {
                    // custom code here
                    klevuMagentoCustomerGroupFlag = true;
                    if(typeof klevu_pageLoadEvent == "function"){
                        klevu_pageLoadEvent() ;
                    }
                    clearInterval(timeKlevuUpdate);
                } else {
                    counter++;
                    if (counter > 7) {
                        klevuMagentoCustomerGroupFlag = true;
                        if(typeof klevu_pageLoadEvent == "function"){
                            klevu_pageLoadEvent() ;
                        }
                        clearInterval(timeKlevuUpdate);
                    }
                }
            }, 700);
    </script>
<?php } ?>
