<?php /** @var \Klevu\Search\Block\Catalog\Product\Tracking $block */ ?>
<?php if ($block->isExtensionConfigured()) : ?>
    <script type="text/javascript">
        var referrer, search_term, klevu_search_product_tracking;
        referrer = document.referrer;
        var getQueryString = function (field, url) {
            var href = url ? url : window.location.href;
            var reg = new RegExp('[?&]' + field + '=([^&#]*)', 'i');
            var string = reg.exec(href);
            if (!string) {
                return null;
            }

            return decodeURIComponent(string[1].replace(/\+/g, " "));
        };
        search_term = getQueryString('q', referrer);

        if (referrer.indexOf('catalogsearch/result') > -1 && search_term) {
            klevu_search_product_tracking = <?= $block->getJsonTrackingData() ?>;
            klevu_search_product_tracking.klevu_term = search_term;

            let searchParams = new URLSearchParams();

            for (let key in klevu_search_product_tracking) {
                if (!klevu_search_product_tracking.hasOwnProperty(key)) {
                    continue;
                }
                searchParams.append(key, klevu_search_product_tracking[key])
            }

            const url = '<?= $block->escapeUrl($block->getAnalyticsUrl()) ?>'+ searchParams.toString();

            fetch(url, {
                method: 'GET',
                crossDomain: true
            }).then(response => {
            });

        }
    </script>
<?php endif; ?>