<?php /** @var \Klevu\Search\Block\Catalog\Product\Tracking $block */ ?>
<?php if ($block->isExtensionConfigured()) : ?>
<script type="text/javascript">
require(['jquery'], function(){
        var referrer, search_term, klevu_search_product_tracking;
        referrer = document.referrer;
        var getQueryString = function ( field, url ) {
            var href = url ? url : window.location.href;
            var reg = new RegExp( '[?&]' + field + '=([^&#]*)', 'i' );
            var string = reg.exec(href);
                return string ? string[1] : null;
        };
        search_term = getQueryString('q',referrer);
        if (referrer.indexOf('catalogsearch/result') > -1 && search_term) {
            klevu_search_product_tracking = <?php echo $block->getJsonTrackingData() ?>;
            klevu_search_product_tracking.klevu_term = search_term;
            var param = jQuery.param(klevu_search_product_tracking);
            jQuery.ajax({
                url:'//<?php echo $block->getAnalyticsUrl() ?>/analytics/productTracking',
                type: 'GET',
                data: param,
                dataType: 'json',
                statusCode: {
                    200: function(data) {
                    }
                },
                crossDomain: true
            });
        }
});
</script>
<?php endif; ?>
