<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?= $block->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
<div class="kuWizardSteps">
<ol class="wizard-progress clearfix">
    <li class="active-step">
        <span class="step-name"><?= /** @noEscape */ __("Register/Login");?></span>
        <span class="visuallyhidden"><?= /** @noEscape */ __("Step");?> </span><span class="step-num">&nbsp;</span>
    </li>
    <li class="active-step">
        <span class="step-name"><?= /** @noEscape */ __("Select Plan");?></span>
        <span class="visuallyhidden"><?= /** @noEscape */ __("Step");?> </span><span class="step-num">&nbsp;</span>
    </li>
    <li class="active-step">
        <span class="step-name"><?= /** @noEscape */ __("Configure Store");?></span>
        <span class="visuallyhidden"><?= /** @noEscape */ __("Step");?></span><span class="step-num">&nbsp;</span>
    </li>
    <li class="active-step">
        <span class="step-name"><?= /** @noEscape */ __("Finish & Sync");?></span>
        <span class="visuallyhidden"><?= /** @noEscape */ __("Step");?> </span><span class="step-num">&nbsp;</span>
    </li>
</ol>
</div>

<div class="kuFinishSyncInfo">
    <h3><?= /** @noEscape */ __('Please click the "Finish and Sync" button below to synchronise your products to Klevu.Sync will start in new tab');?></h3>

    <ul>
        <li><?= /** @noEscape */ __('Klevu Search will be automatically enabled on frontend after the first synchronisation completes.');?></li>
        <li><?= /** @noEscape */ __('Data will be automatically resynchronised periodically as well as when any information changes.');?></li>
        <li><?= /** @noEscape */ __('Make sure your CRON is setup.');?></li>
    </ul>

    <br/>
    <br/>
    <div class="button-set">
    <button id="sync-button" class="action-default primary"><span><?= /** @noEscape */ __("Finish and Sync") ?></span></button><br/>
</div>
<h4 class="kuCompleteWarning"><?= /** @noEscape */ __('Sync will start in new tab.Please close the wizard when sync starts in new tab.');?></h4>
<script type="text/javascript">
require([
    "jquery",
    'Magento_Ui/js/modal/alert',
    "jquery/ui",
    "jquery/editableMultiselect/js/jquery.multiselect",
    "mage/mage",
    'Magento_Ui/js/modal/modal'
], function($, alert){
    $("#sync-button").on("click", function (e) {
            window.open("<?= /** @noEscape */ $block->getSyncUrlForStore(); ?>","_blank");
    });
});
</script>
</div>
