<?php /** Template copied from: app/design/adminhtml/default/default/template/system/config/form/field/array.phtml */ ?>
<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();

$_colspan = 2;
if (!$block->_addAfter) {
    $_colspan -= 1;
}
$_colspan = $_colspan > 1 ? 'colspan="' . $_colspan . '"' : '';
?>

<div class="grid" id="grid<?= /** @noEscape */ $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tbody>

            <tr class="headings" id="headings<?= /** @noEscape */ $_htmlId ?>">
<?php foreach ($block->_columns as $columnName => $column):?>
                <th><?= /** @noEscape */ $column['label'] ?></th>
<?php endforeach;?>
                <th <?= /** @noEscape */ $_colspan?>></th>
            </tr>

            <tr id="addRow<?= /** @noEscape */ $_htmlId ?>">
                <td colspan="<?= count($block->_columns) ?>"></td>
                <td <?= /** @noEscape */ $_colspan?>>
                    <button style="" onclick="" class="scalable add" type="button" id="addToEndBtn<?= /** @noEscape */ $_htmlId ?>">
                        <span><span><span><?= /** @noEscape */ $block->_addButtonLabel ?></span></span></span>
                    </button>
                </td>
            </tr>

        </tbody>
    </table>
    <input type="hidden" name="<?= /** @noEscape */ $block->getElement()->getName() ?>[__empty]" value="" />
</div>
<div id="empty<?= /** @noEscape */ $_htmlId ?>">
    <button style="" onclick="" class="scalable add" type="button" id="emptyAddBtn<?= /** @noEscape */ $_htmlId ?>">
        <span><span><span><?= /** @noEscape */ $block->_addButtonLabel ?></span></span></span>
    </button>
</div>

<script type="text/javascript">

// create row creator
// Make sure it's in the global scope
window.arrayRow<?= /** @noEscape */ $_htmlId ?> = {
    // define row prototypeJS template
    template : new Template(
        '<tr id="#{_id}">'
<?php foreach ($block->_columns as $columnName => $column):?>
            +'<td>'
                +'<?= /** @noEscape */ $block->_renderCellTemplate($columnName)?>'
            +'<\/td>'
<?php endforeach;?>
<?php if ($block->_addAfter):?>
            +'<td><button onclick="" class="scalable add" type="button" id="addAfterBtn#{_id}"><span><span><span><?= /** @noEscape */ __('Add after') ?><\/span><\/span><\/span><\/button><\/td>'
<?php endif;?>
            +'<td><button onclick="arrayRow<?= /** @noEscape */ $_htmlId ?>.del(\'#{_id}\')" class="scalable delete" type="button"><span><span><span><?= /** @noEscape */ __('Delete') ?><\/span><\/span><\/span><\/button><\/td>'
        +'<\/tr>'
    ),

    rowsCount : 0,

    add : function(templateData, insertAfterId)
    {
        // generate default template data
        if ('' == templateData) {
            var d = new Date();
            var templateData = {
<?php foreach ($block->_columns as $columnName => $column):?>
                <?= /** @noEscape */ $columnName ?> : '',
<?php endforeach;?>
                _id : '_' + d.getTime() + '_' + d.getMilliseconds()
            };
        }

        // insert before last row
        if ('' == insertAfterId) {
            Element.insert($('addRow<?= /** @noEscape */ $_htmlId ?>'), {before: this.template.evaluate(templateData)});
        }
        // insert after specified row
        else {
            Element.insert($(insertAfterId), {after: this.template.evaluate(templateData)});
        }

<?php if ($block->_addAfter):?>
        Event.observe('addAfterBtn' + templateData._id, 'click', this.add.bind(this, '', templateData._id));
<?php endif;?>

        this.rowsCount += 1;
    },

    del : function(rowId)
    {
        $(rowId).remove();
        this.rowsCount -= 1;
        if (0 == this.rowsCount) {
            this.showButtonOnly();
        }
    },

    showButtonOnly : function()
    {
        $('grid<?= /** @noEscape */ $_htmlId ?>').hide();
        $('empty<?= /** @noEscape */ $_htmlId ?>').show();
    }
}

// bind add action to "Add" button in last row
Event.observe('addToEndBtn<?= /** @noEscape */ $_htmlId ?>', 'click', arrayRow<?= /** @noEscape */ $_htmlId ?>.add.bind(arrayRow<?= /** @noEscape */ $_htmlId ?>, '', ''));

// add existing rows
<?php
$_addAfterId = "headings$_htmlId";
foreach ($block->getArrayRows() as $_rowId => $_row) {
    //@codingStandardsIgnoreStart
    echo "arrayRow$_htmlId.add(" . $_row->toJson() . ", '$_addAfterId');\n";
    //@codingStandardsIgnoreEnd
    $_addAfterId = $_rowId;
}
?>

// initialize standalone button
$('empty<?= /** @noEscape */ $_htmlId ?>').hide();
Event.observe('emptyAddBtn<?= /** @noEscape */ $_htmlId ?>', 'click', function () {
    $('grid<?= /** @noEscape */ $_htmlId ?>').show();
    $('empty<?= /** @noEscape */ $_htmlId ?>').hide();
    arrayRow<?= /** @noEscape */ $_htmlId ?>.add('', '');
});

// if no rows, hide grid and show button only
<?php if (!$block->getArrayRows()):?>
arrayRow<?= /** @noEscape */ $_htmlId ?>.showButtonOnly();
<?php endif;?>

// toggle the grid, if element is disabled (depending on scope)
<?php if ($block->getElement()->getDisabled()):?>
toggleValueElements({checked:true}, $('grid<?= /** @noEscape */ $_htmlId ?>').parentNode);
<?php endif;?>

</script>
