<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<tr>
    <td colspan="3">
        <div class="message message-success" id="klevu-integration-success-msg" style="display:none;"></div>
        <div class="message message-warning" id="klevu-integration-warning-msg" style="display:none;"></div>
        <div class="message message-error" id="klevu-integration-error-msg" style="display:none;"></div>
    </td>
</tr>
