<?php /** @var \Klevu\Search\Block\Adminhtml\Form\Field\Sync\Button $block */ ?>
<button id="<?= /** @noEscape */ $block->getHtmlId() ?>" class="scalable" type="button">
    <span><?= /** @noEscape */ __($block->getButtonLabel()) ?></span>
</button>
<script type="text/javascript">
require(["prototype"], function(){
    $("<?= /** @noEscape */ $block->getHtmlId() ?>").observe("click", function () {
        window.open('<?= /** @noEscape */ $block->getDestinationUrl() ?>','_blank');
    });
});
</script>
