<?php /** @var \Klevu\Search\Block\Adminhtml\Form\Field\Sync\UpdatesOnly $block */ ?>
<button id="<?= /** @noEscape */ $block->getHtmlId() ?>" class="scalable" type="button">
    <span><?= /** @noEscape */ __($block->getButtonLabel()); ?></span>
</button>
<script type="text/javascript">
    require(["prototype"], function(){
        $("<?= /** @noEscape */ $block->getHtmlId() ?>").observe("click", function () {
            if(document.getElementById('klevu_search_product_sync_updatesonly_sync_btn')) {
                var syncoptions = <?= /** @noEscape */ $block->getSyncOptionId()?>;
                new Ajax.Request("<?= /** @noEscape */ $block->getUrl('klevu_search/savesyncoption/option'); ?>" + '?sync_options=' + syncoptions, {
                    method: 'POST',
                    onComplete: function(data) {
                        if(syncoptions) {
                            window.open("<?= /** @noEscape */ $block->getSyncUrlForStore(); ?>","_blank");
                        } else {
                            setLocation("<?= /** @noEscape */ $block->getDestinationUrl() ?>");
                        }
                    }
                });
            } else {
                setLocation("<?= /** @noEscape */ $block->getDestinationUrl() ?>");
            }
        });
    });
</script>
