<?php /** @var \Klevu\Search\Block\Adminhtml\Form\Field\Sync\UpdatesOnly $block */ ?>
<button id="<?php echo $block->getHtmlId() ?>" class="scalable" type="button">
    <span><?php echo __($block->getButtonLabel()); ?></span>
</button>
<script type="text/javascript">
    require(["prototype"], function(){
        $("<?php echo $block->getHtmlId() ?>").observe("click", function () {
            if(document.getElementById('klevu_search_product_sync_updatesonly_sync_btn')) {
                var syncoptions = <?php echo $block->getSyncOptionId()?>;
                new Ajax.Request("<?php echo $block->getUrl('klevu_search/savesyncoption/option'); ?>" + '?sync_options=' + syncoptions, {
                    method: 'POST',
                    onComplete: function(data) {
                        if(syncoptions) {
                            window.open("<?php echo $block->getSyncUrlForStore(); ?>","_blank");
                        } else {
                            setLocation("<?php echo $block->getDestinationUrl() ?>");
                        }
                    }
                });
            } else {
                setLocation("<?php echo $block->getDestinationUrl() ?>");
            }
        });
    });
</script>
