<?php /** @var \Klevu\Search\Block\Adminhtml\Wizard\Config\Button $block */ ?>
<button id="<?= /** @noEscape */ $block->getHtmlId() ?>" class="scalable" type="button">
    <span><?= /** @noEscape */ __("Start Configuration Wizard") ?></span>
</button>
<script type="text/javascript">
    require(["prototype"], function(){
        $("<?= /** @noEscape */ $block->getHtmlId() ?>").observe("click", function () {
            new Klevu.Search.Wizard({
                url: "<?= /** @noEscape */ $block->getWizardUrl() ?>"
            });
        });
    });

</script>
