<?php /** @var \Klevu\Search\Block\Adminhtml\Wizard\Config\Button $block */ ?>
<button id="<?php echo $block->getHtmlId() ?>" class="scalable" type="button">
    <span><?php echo __("Start Configuration Wizard") ?></span>
</button>
<script type="text/javascript">
    require(["prototype"], function(){
        $("<?php echo $block->getHtmlId() ?>").observe("click", function () {
            new Klevu.Search.Wizard({
                url: "<?php echo $block->getWizardUrl() ?>"
            });
        });
    });

</script>
