<?php /** @var Klevu\Search\Block\Adminhtml\Form\Field\Integration\NextSteps\Introduction $block */ ?>

<tr class="klevu-next-step-intro">
    <td colspan="3">
        <strong><?= $block->escapeHtml(__('Congratulations!')) ?></strong>
        <?= $block->escapeHtml(__('To finish integrating Klevu with your store, you will need to synchronise your catalog with the Klevu service and enable search on your store front')) ?>
    </td>
</tr>
