<?php
/**
 * @var Klevu\Search\Block\Html\Head\ThemeV2\AddPriceSuffixToQuery $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$quickSearchScriptString = '';
$landingScriptString = '';
?>

<?php if ($block->shouldOutputQuickScript()): ?>
    <?php
    $quickSearchScriptStringChains = "
    klevu.settings.chains.initChain.add({
        name: 'addPriceSuffixToQuickQuery',
        fire: function (data) {
            if (klevu.getObjectPath(klevu.search, 'quick', false)
                && klevu.getGlobalSetting('flags.addPriceSuffixToQuery.quick', false)
                && typeof klevu_addPriceSuffixToQueryControl === 'object'
            ) {
                klevu.search.quick.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                klevu.setObjectPath(data, 'flags.addPriceSuffixToQuery.quick', false);
            }
        }
    });
    ";
    ?>
    <?php
    $quickPowerUp = "
        klevu({ powerUp: { quick: true } });
    ";

    $quickPowerUpWithSuffix = "
         klevu({
            powerUp: { quick: true },
            flags: {
                addPriceSuffixToQuery: {
                    quick: true
                }
            }
        });
    ";
    ?>
    <?php if ($block->isDeferJs()): ?>
        <?php
        $quickSearchScriptString .= "
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            {$quickSearchScriptStringChains}
        });
        var klevuPowerUpQuick = function() {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
                {$quickPowerUp}
            });

            return true;
        };
        var klevuPowerUpQuickWithSuffix = function () {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
               {$quickPowerUpWithSuffix}
            });

            return true;
        };
        ";
        ?>
    <?php else: ?>
        <?php
        $quickSearchScriptString .= "
        {$quickSearchScriptStringChains}

        var klevuPowerUpQuick = function() {
            {$quickPowerUp}

            return true;
        };
        var klevuPowerUpQuickWithSuffix = function () {
            {$quickPowerUpWithSuffix}

            return true;
        };";
        ?>
    <?php endif; ?>
    <?php
    $quickSearchScriptString .= "
    document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
        klevuPowerUpQuick();
    });
    document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
        klevuPowerUpQuickWithSuffix();
    });
    ";
    ?>
<?php endif; ?>

<?php if ($block->shouldOutputLandingScript()): ?>
    <?php
    $landingScriptStringChains = "
    klevu.settings.chains.initChain.add({
        name: 'addPriceSuffixToLandingQuery',
        fire: function (data) {
            if (klevu.getObjectPath(klevu.search, 'landing', false)
                && klevu.getGlobalSetting('flags.addPriceSuffixToQuery.landing', false)
                && typeof klevu_addPriceSuffixToQueryControl === 'object'
            ) {
                klevu.search.landing.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                klevu.setObjectPath(data, 'flags.addPriceSuffixToQuery.landing', false);
            }
        }
    });
    ";
    ?>

    <?php
    $landingPowerUp = "
        klevu({ powerUp: { landing: true } });
    ";

    $landingPowerUpWithSuffix = "
         klevu({
            powerUp: { landing: true },
            flags: {
                addPriceSuffixToQuery: {
                    landing: true
                }
            }
        });
    ";
    ?>

    <?php if ($block->isDeferJs()): ?>
        <?php
        $landingScriptString .= "
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            {$landingScriptStringChains}
        });
        var klevuPowerUpLanding = function() {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
                {$landingPowerUp}
            });

            return true;
        };
        var klevuPowerUpLandingWithSuffix = function () {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
                {$landingPowerUpWithSuffix}
            });

            return true;
        };
        ";
        ?>
    <?php else: ?>
        <?php
        $landingScriptString .= "
        {$landingScriptStringChains}

        var klevuPowerUpLanding = function() {
            {$landingPowerUp}

            return true;
        };
        var klevuPowerUpLandingWithSuffix = function () {
            {$landingPowerUpWithSuffix}

            return true;
        };
        ";
        ?>
    <?php endif; ?>
    <?php
    $landingScriptString .= "
        document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
            klevuPowerUpLanding();
        });
        document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
            klevuPowerUpLandingWithSuffix();
        });
    ";
    ?>
<?php endif; ?>

<?php if (strlen($quickSearchScriptString) || strlen($landingScriptString)): ?>
    <?php $scriptString = $quickSearchScriptString . PHP_EOL . $landingScriptString; ?>

    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        [
            'type' => 'text/javascript',
            'id' => 'klevu_search_pricesuffix',
        ],
        $scriptString,
        false
    ) ?>
<?php endif; ?>
