<?php
/**
 * @var Klevu\Search\Block\Html\Head\ThemeV2\AddPriceSuffixToQuery $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$scriptString = <<<script

    if ({$block->shouldOutputQuickScript()}) {
        klevu.settings.chains.initChain.add({
            name: "addPriceSuffixToQuickQuery",
            fire: function (data) {
                if (klevu.getObjectPath(klevu.search, "quick", false)
                    && klevu.getGlobalSetting("flags.addPriceSuffixToQuery.quick", false)
                    && typeof klevu_addPriceSuffixToQueryControl === "object"
                ) {
                    klevu.search.quick.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                    klevu.setObjectPath(data, "flags.addPriceSuffixToQuery.quick", false);
                }
            }
        });
        document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
            klevu({ powerUp: { quick: true } });
        });
        document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
            klevu({
                powerUp: { quick: true },
                flags: {
                    addPriceSuffixToQuery: {
                        quick: true
                    }
                }
            });
        });
    }

    if ({$block->shouldOutputLandingScript()}) {
        klevu.settings.chains.initChain.add({
            name: "addPriceSuffixToLandingQuery",
            fire: function (data) {
                if (klevu.getObjectPath(klevu.search, "landing", false)
                    && klevu.getGlobalSetting("flags.addPriceSuffixToQuery.landing", false)
                    && typeof klevu_addPriceSuffixToQueryControl === "object"
                ) {
                    klevu.search.landing.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                    klevu.setObjectPath(data, "flags.addPriceSuffixToQuery.landing", false);
                }
            }
        });

        document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
            klevu({ powerUp: { landing: true } });
        });
        document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
            klevu({ powerUp: { landing: true },
                flags: {
                    addPriceSuffixToQuery: {
                        landing: true
                    }
                }
            });
        });
    }

script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>
