<?php
/**
 * @var Klevu\Search\Block\Html\Head\ThemeV2\InlineCurrencyTranslation $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$quickSearchScriptString = '';
$landingScriptString = '';

if ($block->shouldOutputQuickScript()) {
    $quickSearchScriptString = <<<script
        klevu.settings.chains.initChain.add({
            name: "addCurrencyTranslationToQuick",
            fire: function (data) {
                if (!klevu.getObjectPath(klevu.search, "quick", false)
                    || klevu.search.quick.getScope().chains.response.success.indexOf("processQuery") <= 0
                    || klevu.getGlobalSetting("flags.currencyTranslationAdded.quick", false)
                ) {
                    return;
                }

                klevu.search.quick.getScope().chains.response.success.addAfter("processQuery", {
                    name: "addCurrencyTranslation",
                    fire: function (data, scope) {
                        klevu.search.modules.mageConvertPriceRecordCurrencyData(klevu.getObjectPath(data, "template.query.productList.result"), klevu_currentCurrencyCode, klevu_currentCurrencyRates);
                    }
                });
                klevu.setObjectPath(data, "flags.currencyTranslationAdded.quick", true);
            }
        });

script;
}

if ($block->shouldOutputLandingScript()) {
    $landingScriptString = <<<script
        klevu.settings.chains.initChain.add({
            name: "addCurrencyTranslationToLanding",
            fire: function (data) {
                if (!klevu.getObjectPath(klevu.search, "landing", false)
                    || klevu.search.landing.getScope().chains.response.success.indexOf("processQuery") <= 0
                    || klevu.getGlobalSetting("flags.currencyTranslationAdded.landing", false)
                ) {
                    return;
                }

                klevu.search.landing.getScope().chains.response.success.addAfter("processQuery", {
                    name: "addCurrencyTranslation",
                    fire: function (data, scope) {
                        klevu.search.modules.mageConvertPriceRecordCurrencyData(klevu.getObjectPath(data, "template.query.productList.result"), klevu_currentCurrencyCode, klevu_currentCurrencyRates);
                    }
                });
                klevu.setObjectPath(data, "flags.currencyTranslationAdded.landing", true);
            }
        });

script;
}
?>

<?php if (strlen($quickSearchScriptString) || strlen($landingScriptString)): ?>
    <?= $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        $quickSearchScriptString . $landingScriptString,
        false
    ) ?>
<?php endif; ?>
