<?php
/**
 * @var Klevu\Search\Block\Html\Head\ThemeV2\JsVariables $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$currencyCurrencyRates = $block->getCurrentCurrencyRates();
$isPubInUse = $block->isPubInUse() ? 'true' : 'false';
$outputCurrencyRates = $currencyCurrencyRates
    ? 'var klevu_currentCurrencyRates = {' . $currencyCurrencyRates .'};'
    : '';
$klevuPriceFormatterConfigurationSerialized = $block->getKlevuPriceFormatterConfigurationSerialized();
?>

<?php
$scriptString = "

    var klevu_lang = '{$block->escapeJsQuote($block->getStoreLanguage())}';
    var klevu_baseCurrencyCode = '{$block->escapeJsQuote($block->getBaseCurrencyCode())}';
    var klevu_currentCurrencyCode = '{$block->escapeJsQuote($block->getCurrentCurrencyCode())}';
    {$outputCurrencyRates}
    var klevu_pubIsInUse = {$isPubInUse};
    var klevu_current_version = '{$block->escapeJsQuote($block->getModuleVersion('Klevu_Search'))}';
";

if ($klevuPriceFormatterConfigurationSerialized) {
    $scriptString .= "
    if (typeof klevu_uc_userOptions === 'undefined') {
        klevu_uc_userOptions = {}
    }

    klevu_uc_userOptions.priceFormatter = {$klevuPriceFormatterConfigurationSerialized};
    ";
}
?>
<?= /* @noEscape */ $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>
