<?php
/**
 * @var Klevu\Search\Block\Html\Head\ThemeV2\JsVariables $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$currencyCurrencyRates = $block->getCurrentCurrencyRates();
$isPubInUse = $block->isPubInUse() ? 'true' : 'false';
$outputCurrencyRates = $currencyCurrencyRates
    ? 'var klevu_currentCurrencyRates = ' . $currencyCurrencyRates .';'
    : '';
?>

<?php
$scriptString = <<<script

    var klevu_lang = '{$block->escapeJsQuote($block->getStoreLanguage())}';
    var klevu_baseCurrencyCode = '{$block->escapeJsQuote($block->getBaseCurrencyCode())}';
    var klevu_currentCurrencyCode = '{$block->escapeJsQuote($block->getCurrentCurrencyCode())}';
    {$outputCurrencyRates}
    var klevu_pubIsInUse = {$isPubInUse};
    var klevu_current_version = '{$block->escapeJsQuote($block->getModuleVersion('Klevu_Search'))}';

script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>
