<?php
/** @noinspection PhpUnhandledExceptionInspection */

use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\Catalog\Model\Product\Visibility;
use Magento\Eav\Model\Config as EavConfig;
use Magento\Store\Model\StoreManagerInterface;
use Magento\TestFramework\Helper\Bootstrap;

$objectManager = Bootstrap::getObjectManager();

/** @var StoreManagerInterface $storeManager */
$storeManager = $objectManager->get(StoreManagerInterface::class);
$defaultStoreView = $storeManager->getDefaultStoreView();

/** @var EavConfig $eavConfig */
$eavConfig = $objectManager->get(EavConfig::class);

$configurableAttribute = $eavConfig->getAttribute('catalog_product', 'klevu_synctest_configurable');
$configurableAttributeOptions = $configurableAttribute->getOptions();
array_shift($configurableAttributeOptions); // Clear out the empty option

$fixtures = [];
$productConfigurations = [
    'enabled' => ['status' => Status::STATUS_ENABLED],
    'disabled' => ['status' => Status::STATUS_DISABLED],

    'catalog-search' => ['visibility' => Visibility::VISIBILITY_BOTH],
    'catalog' => ['visibility' => Visibility::VISIBILITY_IN_CATALOG],
    'search' => ['visibility' => Visibility::VISIBILITY_IN_SEARCH],
    'notvisible' => ['visibility' => Visibility::VISIBILITY_NOT_VISIBLE],

    'in-stock-has-qty' => [
        'stock_data' => [
            'use_config_manage_stock' => 1,
            'qty' => 100,
            'is_qty_decimal' => 0,
            'is_in_stock' => 1,
        ],
    ],
    'in-stock-no-qty' => [
        'stock_data' => [
            'use_config_manage_stock' => 1,
            'qty' => 0,
            'is_qty_decimal' => 0,
            'is_in_stock' => 1,
        ],
    ],
    'out-of-stock-has-qty' => [
        'stock_data' => [
            'use_config_manage_stock' => 1,
            'qty' => 100,
            'is_qty_decimal' => 0,
            'is_in_stock' => 0,
        ],
    ],
];

$simpleProductCombinations = [
    // The following test that Disabled products are not included
    ['disabled', 'catalog-search', 'in-stock-has-qty'],
    ['disabled', 'catalog', 'in-stock-has-qty'],
    ['disabled', 'search', 'in-stock-has-qty'],
    ['disabled', 'notvisible', 'in-stock-has-qty'],

    // The following test impact of visibility
    ['enabled', 'catalog-search', 'in-stock-has-qty'],
    ['enabled', 'catalog', 'in-stock-has-qty'],
    ['enabled', 'search', 'in-stock-has-qty'],
    ['enabled', 'notvisible', 'in-stock-has-qty'],

    // The following test impact of stock
//    ['enabled', 'notvisible', 'in-stock-has-qty'], // Left for reference, but duplicates previous fixture
    ['enabled', 'notvisible', 'in-stock-no-qty'],
    ['enabled', 'notvisible', 'out-of-stock-has-qty'],
    ['enabled', 'catalog-search', 'out-of-stock-has-qty'],
    ['enabled', 'catalog-search', 'in-stock-no-qty'],
];
$simpleProductSkus = [];
foreach ($simpleProductCombinations as $i => $simpleProductCombination) {
    // This data file is used in rollback fixtures where the attribute may not have been created / populated
    $configurableAttributeValue = !empty($configurableAttributeOptions)
        ? $configurableAttributeOptions[$i + 1]->getValue()
        : null;

    $sku = vsprintf('klevu_synctest_smp_%s_%s_%s', $simpleProductCombination);
    $simpleProductSkus[] = $sku;

    // Boilerplate setup of fixtures doesn't carry the same performance concern in tests. Let's disable
    // phpcs:disable Magento2.Performance.ForeachArrayMerge.ForeachArrayMerge
    $fixtures[] = array_merge(
        [
            'type_id' => 'simple',
            'sku' => $sku,
            'name' => vsprintf('[Klevu] Sync Test Simple Product (%s; %s; %s)', $simpleProductCombination),
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'klevu_synctest_configurable' => $configurableAttributeValue,
            'url_key' => $sku . '_' . crc32(rand()),
        ],
        ...array_map(function ($configurationKey) use ($productConfigurations) {
            return $productConfigurations[$configurationKey];
        }, $simpleProductCombination)
    );
    // phpcs:enable Magento2.Performance.ForeachArrayMerge.ForeachArrayMerge
}

$configurableProductCombinations = [
    // The following test that Disabled products are not included
    ['disabled', 'catalog-search', 'in-stock-has-qty'],
    ['disabled', 'catalog', 'in-stock-has-qty'],
    ['disabled', 'search', 'in-stock-has-qty'],
    ['disabled', 'notvisible', 'in-stock-has-qty'],

    // The following test impact of visibility
    ['enabled', 'catalog-search', 'in-stock-has-qty'],
    ['enabled', 'catalog', 'in-stock-has-qty'],
    ['enabled', 'search', 'in-stock-has-qty'],
    ['enabled', 'notvisible', 'in-stock-has-qty'],

    // The following test impact of stock
//    ['enabled', 'notvisible', 'in-stock-has-qty'], // Left for reference, but duplicates previous fixture
    ['enabled', 'catalog-search', 'out-of-stock-has-qty'],
];
foreach ($configurableProductCombinations as $configurableProductCombination) {
    $sku = vsprintf('klevu_synctest_conf_%s_%s_%s', $configurableProductCombination);

    // Boilerplate setup of fixtures doesn't carry the same performance concern in tests. Let's disable
    // phpcs:disable Magento2.Performance.ForeachArrayMerge.ForeachArrayMerge
    $fixtures[] = array_merge(
        [
            'type_id' => 'configurable',
            'sku' => $sku,
            'name' => vsprintf('[Klevu] Sync Test Configurable Product(%s; %s; %s)', $configurableProductCombination),
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'url_key' => $sku . '_' . crc32(rand()),
            'child_skus' => $simpleProductSkus,
        ],
        ...array_map(function ($configurationKey) use ($productConfigurations) {
            return $productConfigurations[$configurationKey];
        }, $configurableProductCombination)
    );
    // phpcs:enable Magento2.Performance.ForeachArrayMerge.ForeachArrayMerge
}

$fixtures = array_merge(
    $fixtures,
    [
        // Grouped
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-y_v-both',
            'name' => '[Klevu] Grouped Product 1',
            'description' => '[Klevu Test Fixtures] Grouped Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-y-v-both' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-y_v-catalog',
            'name' => '[Klevu] Grouped Product 2',
            'description' => '[Klevu Test Fixtures] Grouped Product 2 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-y-v-catalog' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-y_v-search',
            'name' => '[Klevu] Grouped Product 3',
            'description' => '[Klevu Test Fixtures] Grouped Product 3 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-y-v-search' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-y_v-none',
            'name' => '[Klevu] Grouped Product 4',
            'description' => '[Klevu Test Fixtures] Grouped Product 4 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-y-v-none' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-n_v-both',
            'name' => '[Klevu] Grouped Product 5',
            'description' => '[Klevu Test Fixtures] Grouped Product 5 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-n-v-both' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-n_v-catalog',
            'name' => '[Klevu] Grouped Product 6',
            'description' => '[Klevu Test Fixtures] Grouped Product 6 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-n-v-catalog' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-n_v-search',
            'name' => '[Klevu] Grouped Product 7',
            'description' => '[Klevu Test Fixtures] Grouped Product 7 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-n-v-search' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'grouped',
            'sku' => 'klevu_synctest_grouped_en-n_v-none',
            'name' => '[Klevu] Grouped Product 8',
            'description' => '[Klevu Test Fixtures] Grouped Product 8 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'tax_class_id' => 2,
            'url_key' => 'klevu-synctest-grouped-en-n-v-none' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'associated_skus' => $simpleProductSkus
        ],
        // Bundle
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-both-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-both-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-search-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-search-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-catalog-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-catalog-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-none-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-none-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-n_v-both-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: Both; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-n_v-both-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-n_v-search-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: Search; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-n_v-catalog-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-n_v-catalog-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-n_v-catalog-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-n_v-none-s-yes',
            'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: None; In Stock: Yes)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_bundle_en-n_v-none-s-yes' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-both-s-no',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Both; In Stock: No)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-both-s-no' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-search-s-no',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Search; In Stock: No)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-catalog-s-no' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-catalog-s-no',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-catalog-s-no' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        [
            'type_id' => 'bundle',
            'sku' => 'klevu_synctest_bundle_en-y_v-none-s-no',
            'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: None; In Stock: No)',
            'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 100.00,
            'weight' => 12,
            'meta_title' => '[Klevu] Bundle Product Test',
            'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
            'tax_class_id' => 2,
            'price_type' => \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_bundle_en-y_v-none-s-no' . crc32(rand()),
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'associated_skus' => $simpleProductSkus
        ],
        // Virtual
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-both_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-both_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-both_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Both; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 11.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-both_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-search_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-search_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-search_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Search; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 15.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-search_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-catalog_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-catalog_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-catalog_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-catalog_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-none_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-none_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-y_v-none_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: None; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-y_v-none_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-both_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Both; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-both_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-both_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Both; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 11.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-both_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-search_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Search; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-search_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-both_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Search; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 15.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-search_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-catalog_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-catalog_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-catalog_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Catalog; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-catalog_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-none_s-yes',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: None; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-none_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'virtual',
            'sku' => 'klevu_synctest_virtual_en-n_v-none_s-no',
            'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: None; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 50.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_virtual_en-n_v-none_s-no_' . crc32(rand()),
        ],
        // Downloadable
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-both_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-both_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-both_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Both; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 11.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-both_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-search_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-search_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-search_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Search; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 15.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-search_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-catalog_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-catalog_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-catalog_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-catalog_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-none_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-none_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-y_v-none_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: None; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-y_v-none_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-both_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Both; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-both_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-both_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Both; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 11.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-both_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-search_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Search; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-search_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-both_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Search; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 15.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-search_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-catalog_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-catalog_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-catalog_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Catalog; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-catalog_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-none_s-yes',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: None; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-none_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'downloadable',
            'sku' => 'klevu_synctest_downloadable_en-n_v-none_s-no',
            'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: None; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 50.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_downloadable_en-n_v-none_s-no_' . crc32(rand()),
        ],
        // Giftcard
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-both_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-both_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-both_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Both; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 11.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-both_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-search_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-search_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-search_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Search; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 15.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-search_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-catalog_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-catalog_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-catalog_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-catalog_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-none_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-none_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-y_v-none_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: None; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_ENABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-y_v-none_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-both_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Both; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-both_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-both_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Both; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 11.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_BOTH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-both_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-search_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Search; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-search_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-both_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Search; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 15.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_SEARCH,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-search_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-catalog_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-catalog_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-catalog_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Catalog; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_IN_CATALOG,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-catalog_s-no_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-none_s-yes',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: None; In Stock: Yes)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 10.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 1,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-none_s-yes_' . crc32(rand()),
        ],
        [
            'type_id' => 'giftcard',
            'sku' => 'klevu_synctest_giftcard_en-n_v-none_s-no',
            'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: None; In Stock: No)',
            'description' => '',
            'short_description' => '',
            'attribute_set_id' => 4,
            'website_ids' => [
                $defaultStoreView->getWebsiteId(),
            ],
            'price' => 50.00,
            'weight' => 1,
            'tax_class_id' => 2,
            'meta_title' => '[Klevu] Sync Test Fixtures',
            'meta_description' => '',
            'giftcard_type' => 1,
            'allow_open_amount' => 1,
            'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
            'status' => Status::STATUS_DISABLED,
            'stock_data' => [
                'use_config_manage_stock' => 1,
                'qty' => 100,
                'is_qty_decimal' => 0,
                'is_in_stock' => 0,
            ],
            'url_key' => 'klevu_synctest_giftcard_en-n_v-none_s-no_' . crc32(rand()),
        ]
    ]
);
