<?php
/** @noinspection PhpUnhandledExceptionInspection */

use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\Catalog\Model\Product\Visibility;
use Magento\Eav\Model\Config as EavConfig;
use Magento\Store\Model\StoreManagerInterface;
use Magento\TestFramework\Helper\Bootstrap;

$objectManager = Bootstrap::getObjectManager();

/** @var StoreManagerInterface $storeManager */
$storeManager = $objectManager->get(StoreManagerInterface::class);
$defaultStoreView = $storeManager->getDefaultStoreView();

/** @var EavConfig $eavConfig */
$eavConfig = $objectManager->get(EavConfig::class);

$configurableAttribute = $eavConfig->getAttribute('catalog_product', 'klevu_test_configurable');
$configurableAttributeOptions = $configurableAttribute->getOptions();

$fixtures = [
    // Simple
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-both_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-both_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-search_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-search_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-catalog_s-yes_' . md5(rand()),
    ],[
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-none_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-y_v-none_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: Yes; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-y_v-none_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-both_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-search_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-catalog_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-none_s-yes',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'simple',
        'sku' => 'klevu_synctest_simple_en-n_v-none_s-no',
        'name' => '[Klevu] Sync Test Simple Product (Enabled: No; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 50.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_simple_en-n_v-none_s-no_' . md5(rand()),
    ],
    // Configurable
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-both_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: Both, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_configurable_en-y_v-both_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-search_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: Search, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu-configurable-product_en-y_v-search_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-catalog_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: Catalog, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu-configurable-product_en-y_v-catalog_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-none_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: None, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu-configurable-product_en-y_v-none_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-both_s-no_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: Both, Stock: No, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_configurable_en-y_v-both_s-no_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-search_s-no_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: Search, Stock: No, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu-configurable-product_en-y_v-search_s-no_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-catalog_s-no_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: Catalog, Stock: No, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu-configurable-product_en-y_v-catalog_s-no_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-y_v-none_s-no_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: None, Stock: No, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu-configurable-product_en-y_v-none_s-no_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-n_v-both_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: Yes, Visibility: Both, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu-configurable-product_en-n_v-both_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-n_v-search_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: No, Visibility: Search, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu-configurable-product_en-n_v-both_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-n_v-catalog_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: No, Visibility: Catalog, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu-configurable-product_en-n_v-catalog_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    [
        'type_id' => 'configurable',
        'sku' => 'klevu_synctest_configurable_en-n_v-none_s-yes_chd-yes',
        'name' => '[Klevu] Configurable Product (Enabled: No, Visibility: None, Stock: Yes, Child: Yes)',
        'description' => '[Klevu Test Fixtures] Configurable product',
        'short_description' => '1 child enabled and in stock',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Configurable Product',
        'meta_description' => '[Klevu Test Fixtures] Configurable product',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu-configurable-product_en-n_v-none_s-yes_chd-yes' . md5(rand()),
        'child_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes',
        ],
    ],
    // Grouped
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-y_v-both',
        'name' => '[Klevu] Grouped Product 1',
        'description' => '[Klevu Test Fixtures] Grouped Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-y-v-both' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-y_v-catalog',
        'name' => '[Klevu] Grouped Product 2',
        'description' => '[Klevu Test Fixtures] Grouped Product 2 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-y-v-catalog' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-y_v-search',
        'name' => '[Klevu] Grouped Product 3',
        'description' => '[Klevu Test Fixtures] Grouped Product 3 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-y-v-search' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-y_v-none',
        'name' => '[Klevu] Grouped Product 4',
        'description' => '[Klevu Test Fixtures] Grouped Product 4 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-y-v-none' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-n_v-both',
        'name' => '[Klevu] Grouped Product 5',
        'description' => '[Klevu Test Fixtures] Grouped Product 5 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-n-v-both' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-n_v-catalog',
        'name' => '[Klevu] Grouped Product 6',
        'description' => '[Klevu Test Fixtures] Grouped Product 6 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-n-v-catalog' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-n_v-search',
        'name' => '[Klevu] Grouped Product 7',
        'description' => '[Klevu Test Fixtures] Grouped Product 7 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-n-v-search' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'grouped',
        'sku' => 'klevu_synctest_grouped_en-n_v-none',
        'name' => '[Klevu] Grouped Product 8',
        'description' => '[Klevu Test Fixtures] Grouped Product 8 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'tax_class_id' => 2,
        'url_key' => 'klevu-synctest-grouped-en-n-v-none' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    // Bundle
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-both-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-both-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-search-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-search-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-catalog-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-catalog-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-none-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-none-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-n_v-both-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: Both; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-n_v-both-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-n_v-search-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: Search; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-n_v-catalog-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-n_v-catalog-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-n_v-catalog-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-n_v-none-s-yes',
        'name' => '[Klevu] Bundle Product (Enabled: No; Visibility: None; In Stock: Yes)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_bundle_en-n_v-none-s-yes' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-both-s-no',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Both; In Stock: No)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-both-s-no' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-search-s-no',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Search; In Stock: No)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-catalog-s-no' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-catalog-s-no',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-catalog-s-no' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    [
        'type_id' => 'bundle',
        'sku' => 'klevu_synctest_bundle_en-y_v-none-s-no',
        'name' => '[Klevu] Bundle Product (Enabled: Yes; Visibility: None; In Stock: No)',
        'description' => '[Klevu Test Fixtures] Bundle Product 1 Description',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 100.00,
        'weight' => 12,
        'meta_title' => '[Klevu] Bundle Product Test',
        'meta_description' => '[Klevu Test Fixtures] assigned bundle product',
        'tax_class_id' => 2,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_bundle_en-y_v-none-s-no' . md5(rand()),
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'associated_skus' => [
            'klevu_synctest_simple_en-y_v-both_s-yes'
        ]
    ],
    // Virtual
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-both_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-both_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-search_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-search_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-catalog_s-yes_' . md5(rand()),
    ],[
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-none_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-y_v-none_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: Yes; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-y_v-none_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-both_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-search_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-catalog_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-none_s-yes',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'virtual',
        'sku' => 'klevu_synctest_virtual_en-n_v-none_s-no',
        'name' => '[Klevu] Sync Test Virtual Product (Enabled: No; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 50.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_virtual_en-n_v-none_s-no_' . md5(rand()),
    ],
    // Downloadable
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-both_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-both_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-search_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-search_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-catalog_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-none_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-y_v-none_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: Yes; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-y_v-none_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-both_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-search_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-catalog_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-none_s-yes',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'downloadable',
        'sku' => 'klevu_synctest_downloadable_en-n_v-none_s-no',
        'name' => '[Klevu] Sync Test Downloadable Product (Enabled: No; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 50.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_downloadable_en-n_v-none_s-no_' . md5(rand()),
    ],
    // Giftcard
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-both_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-both_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-search_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-search_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-catalog_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-none_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-y_v-none_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: Yes; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_ENABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-y_v-none_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-both_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Both; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-both_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Both; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 11.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-both_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-search_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Search; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-search_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-both_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Search; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 15.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_SEARCH,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-search_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-catalog_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Catalog; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-catalog_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-catalog_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: Catalog; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_IN_CATALOG,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-catalog_s-no_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-none_s-yes',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: None; In Stock: Yes)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 10.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 1,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-none_s-yes_' . md5(rand()),
    ],
    [
        'type_id' => 'giftcard',
        'sku' => 'klevu_synctest_giftcard_en-n_v-none_s-no',
        'name' => '[Klevu] Sync Test Giftcard Product (Enabled: No; Visibility: None; In Stock: No)',
        'description' => '',
        'short_description' => '',
        'attribute_set_id' => 4,
        'website_ids' => [
            $defaultStoreView->getWebsiteId(),
        ],
        'price' => 50.00,
        'weight' => 1,
        'tax_class_id' => 2,
        'meta_title' => '[Klevu] Sync Test Fixtures',
        'meta_description' => '',
        'visibility' => Visibility::VISIBILITY_NOT_VISIBLE,
        'status' => Status::STATUS_DISABLED,
        'stock_data' => [
            'use_config_manage_stock'   => 1,
            'qty'                       => 100,
            'is_qty_decimal'            => 0,
            'is_in_stock'               => 0,
        ],
        'url_key' => 'klevu_synctest_giftcard_en-n_v-none_s-no_' . md5(rand()),
    ]
];
