<?php /** @var \Klevu\Search\Block\Adminhtml\Form\Field\Integration\Warnings\OrdersSameIp $block */ ?>
<?php if ($block->hasMultipleOrdersWithSameIp()): ?>
    <div class="message message-error">
        <?= $block->escapeHtml(
            __('Klevu has detected many checkout orders originating from the same IP address causing inaccuracies in Klevu sales analytics.')
        ) ?>
        <br>
        <?= /** @noEscape */
        __(
            'Please %1 read this article %2 for more information on how to resolve this issue.',
            '<a href="' . $block->escapeUrl($block->getOrderFromSameIpArticleLink()) . '" target="_blank">',
            '</a>'
        ) . ' '
        ?>
        <?= /** @noEscape */
        __(
            'This warning can be disabled via %1 Notification Settings %2',
            '<a href="' . $block->escapeUrl($block->getNotificationArticleLink()) . '">',
            '</a>'
        )
        ?>
    </div>
<?php endif; ?>
