<?php
/**
 * @var Klevu\Search\Block\Search\Index\ThemeV2 $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$contentMinHeight = $block->getContentMinHeight();
?>

<?php if ($contentMinHeight): ?>
    <?= $secureRenderer->renderStyleAsTag(
        'min-height: ' . /** @noEscape */ $contentMinHeight .'px',
        '.klevuLanding'
    ) ?>
<?php endif; ?>
<div class="klevuLanding"></div>
