<?php /** @var \Klevu\Search\Block\Adminhtml\Wizard\Configure\Store $block */ ?>
<?= /** @noEscape */ $block->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
<div class="kuWizardSteps">
    <ol class="wizard-progress clearfix">
        <li class="active-step">
            <span class="step-name"><?= /** @noEscape */ __("Register/Login"); ?></span>
            <span class="visuallyhidden"><?= /** @noEscape */ __("Step"); ?> </span><span class="step-num">&nbsp;</span>
        </li>
        <li class="active-step">
            <span class="step-name"><?= /** @noEscape */ __("Select Plan"); ?></span>
            <span class="visuallyhidden"><?= /** @noEscape */ __("Step"); ?> </span><span class="step-num">&nbsp;</span>
        </li>
        <li class="active-step">
            <span class="step-name"><?= /** @noEscape */ __("Configure Store"); ?></span>
            <span class="visuallyhidden"><?= /** @noEscape */ __("Step"); ?></span><span class="step-num">&nbsp;</span>
        </li>
        <li>
            <span class="step-name"><?= /** @noEscape */ __("Finish & Sync"); ?></span>
            <span class="visuallyhidden"><?= /** @noEscape */ __("Step"); ?> </span><span class="step-num">&nbsp;</span>
        </li>
    </ol>
</div>
<form id="klevu_search_wizard_configure_store_form" action="<?= /** @noEscape */ $block->getFormActionUrl() ?>" method="POST">
    <div class="klevu_conf_store">
        <fieldset class="fieldset admin__fieldset">
            <input type="hidden" name="form_key" value="<?= /** @noEscape */ $block->getFormKey() ?>" />
            <div class="admin__field field">
            <label for="store" class="label admin__field-label"><?= /** @noEscape */ __("Select a Magento store you want to configure Klevu search for.") ?></label>
                <div class="admin__field-control control">
                    <select name="store" class="select admin__control-select">
                            <option value=""></option>
                            <?php $data = $block->getStoreSelectData() ?>
                            <?php foreach ($data as $website => $groups): ?>
                                <optgroup label="<?= $block->escapeHtml($website) ?>"></optgroup>
                                <?php foreach ($groups as $group => $stores): ?>
                                    <optgroup label="&nbsp;&nbsp;<?= $block->escapeHtml($group) ?>">
                                        <?php foreach ($stores as $store): ?>
                                            <?php /** @var \Magento\Framework\Model\Store $store */ ?>
                                            <option value="<?= /** @noEscape */ $store->getCode() ?>">&nbsp;&nbsp;&nbsp;&nbsp;<?= /** @noEscape */ $block->escapeHtml($store->getName()) ?></option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <?php if ($block->showTaxSettings()): ?>
            <div class="admin__field field">
                    <label for="tax_enable" class="label admin__field-label"><?= /** @noEscape */ __("How do you want to display product prices in search?") ?></label>
                    <div class="admin__field-control control">
                    <select name="tax_enable" id="tax_enable" class="select admin__control-select">
                            <option value="1"><?= /** @noEscape */ __("Excluding Tax"); ?></option>
                            <option value="2"><?= /** @noEscape */ __("Including Tax"); ?></option>
                    </select>
                    </div>
            </div>
            <?php endif; ?>
            <div class="admin__field field">
                    <label for="secure_baseurl_enable" class="label admin__field-label"><?= /** @noEscape */ __("Which 'base URL' would you like to use for products in search results?"); ?><br/>
                    <span class="note">(from System > Configuration > Web > Secure OR Unsecure > Base URL)") </span></label>

                        <div class="admin__field-control control">
                        <select name="secure_baseurl_enable" id="secure_base_enable" class="select admin__control-select">
                            <option value="0" selected="selected"><?= /** @noEscape */ __("Unsecure") ?></option>
                            <option value="1"><?= /** @noEscape */ __("Secure") ?></option>
                        </select>
                        </div>
            </div>
            <?php if ($block->showUseCollectionMethod()): ?>
            <div class="admin__field field">
                <label for="collection_method" class="label admin__field-label"><?= /** @noEscape */ __('Use Collection Method'); ?> <br/>
                </label>
                <div class="admin__field-control control">
                    <select name="use_collection_method" id="use_collection_method" class="select admin__control-select">
                    <option value="1"><?= /** @noEscape */ __('Yes');?> </option>
                    <option value="0"><?= /** @noEscape */ __('No');?></option>
                    </select><br/>
                    <div id="toshowcollectionnote" class="note" style="font-size: 13px;">
                <?= /** @noEscape */ __('As store having a large number of products, we recommended to ');?>
<a target="_blank" title="<?= /** @noEscape */ __('More info about Collection Method');?>"
   href="https://help.klevu.com/support/solutions/articles/5000871455-sync-data-using-collection-method/">
                <?= /** @noEscape */ __(' Use Collection Method');?></a> and
<a target="_blank" title="<?= /** @noEscape */ __('Guide to Setup Klevu CRON independent of Magento CRON');?>"
   href="https://help.klevu.com/support/solutions/articles/5000871452-setup-external-cron-job">
                <?= /** @noEscape */ __('To Setup Klevu CRON independent of Magento CRON');?></a>
                    </br><strong style="color:red">Warning! </strong><span><?= /** @noEscape */ __('Please make it absolutely sure that Magento Indexers (System > Index Management) are up to date.');?></span>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div class="admin__field field">
                <div class="button-set">
                    <button type="submit" class="action-default primary"><span><?= /** @noEscape */ __("Continue") ?></span></button>
                </div>
            </div>
        </fieldset>
        </div>
</form>
