<?php /** @var \Klevu\Search\Block\Adminhtml\Wizard\Configure\User $block */ ?>
    <?php
echo $block->getLayout()->getMessagesBlock()->getGroupedHtml();
$request = $block->getRequest(); ?>
            <div class="kuWizardSteps">
                <ol class="wizard-progress clearfix">
                    <li class="active-step">
                        <span class="step-name">Register/Login</span>
                        <span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
                    </li>
                    <li>
                        <span class="step-name">Select Plan</span>
                        <span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
                    </li>
                    <li>
                        <span class="step-name">Configure Store</span>
                        <span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
                    </li>
                    <li>
                        <span class="step-name">Finish & Sync</span>
                        <span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
                    </li>
                </ol>
            </div>

            <div class="klevu_registeration">
			    <div class="klevu_login_form" id="klevu_login_form">
				        <form id="klevu_search_wizard_configure_user_form" action="<?php echo $block->getFormActionUrl() ?>" method="POST">
                    <input type="hidden" name="form_key" value="<?php /** @noEscape */ echo $block->getFormKey() ?>" />
                    <input type="hidden" name="store_id" value="<?php echo $block->escapeHtmlAttr($request->getParam('store')); ?>" />
                    <fieldset class="fieldset admin__fieldset">

                        <legend class="legend">
                            <span>Login</span>
                        </legend>

                        <div class="admin__field field">
                            <label for="klevu_existing_email" class="label admin__field-label">
                                <?php echo __("Primary Email:") ?><span class="required">&nbsp;<em>*</em></span></label>

                            <div class="admin__field-control control">
                                <input type="text" name="klevu_existing_email" id="klevu_existing_email" class="input-text admin__control-text" />
                            </div>
                        </div>

                        <div class="admin__field field">
                            <label for="klevu_existing_password" class="label admin__field-label">
                                <?php echo __("Password:") ?><span class="required">&nbsp;<em>*</em></span></label>

                            <div class="admin__field-control control">
                                <input type="password" name="klevu_existing_password" id="klevu_existing_password" class="input-text admin__control-text" />
                            </div>
                        </div>

                        <div class="admin__field field">
                            <div class="button-set">
                                <button type="submit" class="action-default primary"><span><?php echo __("Login") ?></span></button>
                            </div>
                        </div>
                    </fieldset>
					</form>
					<div class="formLinkBlock">Don't have an account?<a class="formLink" href="#" onClick="hide_registration()">Sign up</a></div>
					<div class="formLinkBlock"><a class="formLink" href="https://box.klevu.com/analytics/km?cmd=forgotPasswordPg" target="_blank">Forgot Password?</a></div>
                </div>
                <div class="klevu_signup_form" id="klevu_signup_form" style="display:none;">
                    <form id="klevu_search_wizard_configure_user_form" action="<?php echo $block->getFormActionUrl() ?>" method="POST">
                        <input type="hidden" name="form_key" value="<?php /** @noEscape */ echo $block->getFormKey() ?>" />
                        <input type="hidden" name="store_id" value="<?php echo $block->escapeHtmlAttr($request->getParam('store')); ?>" />

                        <fieldset class="fieldset admin__fieldset">
                        <legend class="legend">
                            <span>Register New User</span>
                            <p>
                                <?php echo __("Fill out the form below to create a new Klevu user.") ?>
                            </p>
                        </legend>
                        <div class="admin__field field">
                            <label class="label admin__field-label" for="klevu_new_email">
                                <?php echo __("Primary Email:") ?><span class="required">&nbsp;<em>*</em></span></label>

                            <div class="admin__field-control control">
                                <input type="text" name="klevu_new_email" value="<?php if($request->getPost(" klevu_new_email ")){ echo $request->getPost("klevu_new_email ");} ?>" id="klevu_new_email" class="input-text admin__control-text required-entry" />
                                <div class="note">
                                    <?php echo __("For login and technical support");?>
                                </div>
                            </div>
                        </div>

                        <div class="admin__field field">
                            <label class="label admin__field-label" for="merchantEmail">
                                <?php echo __("Retailer Email:") ?><span class="required">&nbsp;<em>*</em></span></label>

                            <div class="admin__field-control control">
                                <input type="text" name="merchantEmail" value="<?php if($request->getPost(" merchantEmail ")){ echo $request->getPost("merchantEmail ");} ?>" id="merchantEmail" class="input-text admin__control-text" />
                                <div class="note">
                                    <?php echo __("For search insights and billing");?>
                                </div>
                            </div>
                        </div>

                        <div class="admin__field field">
                            <label class="label admin__field-label" for="klevu_new_password">
                                <?php echo __("Password:") ?><span class="required">&nbsp;<em>*</em></span></label>

                            <div class="admin__field-control control">
                                <input type="password" name="klevu_new_password" id="klevu_new_password" class="input-text admin__control-text" />
                            </div>
                        </div>

                        <div class="admin__field field">
                            <label class="label admin__field-label" for="contactNo">
                                <?php echo __("Phone Number:") ?><span class="required">&nbsp;</span></label>
                            <div class="admin__field-control control">
                                <input type="text" value="<?php if($request->getPost(" countyCode ")){ echo $request->getPost("countyCode ");} ?>" name="countyCode" id="countyCode" class="input-text admin__control-text" />
                                <input type="text" name="contactNo" id="contactNo" value="<?php echo $block->getStorePhoneNumber(); ?>" class="input-text admin__control-text" />
                            </div>
                        </div>

                        <div class="admin__field field">
                            <label class="label admin__field-label" for="klevu_new_url">
                                <?php echo __("Store URL:") ?><span class="required">&nbsp;<em>*</em></span></label>

                            <div class="admin__field-control control">
                                <input type="text" name="klevu_new_url" id="klevu_new_url" class="input-text admin__control-text" value="<?php echo $block->getStoreUrl() ?>" />
                            </div>

                        </div>

                        <div class="admin__field-control control admin__scope-old klevu_terms">
                            <input type="checkbox" name="termsconditions" id="termsOfService" class="checkbox website-checkbox">
                            <label for="termsOfService">I accept
                                <a href="#" onClick="termsofservice();" style="font-size:11px;">
                                    <?php echo __("Terms of Service");?>
                                </a>
                            </label>
                        </div>

                        <div class="admin__field field">
                            <div class="button-set">
                                <button type="submit" class="action-default primary"><span><?php echo __("Next") ?></span></button>
                            </div>
                        </div>
                    </fieldset>
					</form>
					<div class="formLinkBlock"><?php echo __("Already have an account?");?><a href="#" class="formLink" onClick="hide_registration();">click here</a> <?php echo __("to login.") ?></a></div>
                </div>

            </div>

<script>
function hide_registration() {
	var x = document.getElementById('klevu_signup_form');
	var y = document.getElementById('klevu_login_form');
    if (x.style.display === 'none') {
        x.style.display = 'block';
		y.style.display = 'none';
    } else {
        x.style.display = 'none';
		y.style.display = 'block';
    }
}
</script>
